#!/bin/sh
# Write rtl/rf_build_stamp.vh -- ddhhmmss of this compile, as a hex constant.
#
# The self-test page prints it. MiSTer's own build_id.v is date-only AND is
# regenerated by the build flow (which is why the stamp cannot live there), so
# it cannot tell two builds on the same day apart -- exactly the ambiguity
# that turns "is the board running my change?" into a wasted round trip.
set -e
cd "$(dirname "$0")/.."
STAMP=$(date +%d%H%M%S)
cat > rtl/rf_build_stamp.vh <<EOT
// GENERATED by tools/make_build_stamp.sh -- do not edit.
// ddhhmmss of the compile, shown on the self-test page.
\`define RF_BUILD_HEX 32'h${STAMP}
EOT
echo "build stamp ${STAMP}"
